module.exports = [
	{
		id: 1,
		name: "Allspice",
		latin: "Pimenta dioica",
		// img: "https://cdn.pixabay.com/photo/2018/04/22/13/40/cooking-3341063_960_720.jpg",
		img: "../orange/images/allspice-sm-Enotovyj-pixabay.jpg",
		thumb: "../orange/images/thumbnails/allspice-thumb-pixabay.jpg",
		color: "chocolate",
		pSource: " tree berries - Mexico",
		pColor: "Color: brown, burnt sienna",
		pFlavor: "Flavor: savory, spicy",
		pUses: "Uses: pickling, marinades, baking",
		weight: 2,	//2 oz default size
		cost: "$4.59",
		imgId: "all-img",
		subId: "all-sub",
		addId: "all-add",
		amtId: "all-amt",
		savId: "all-sav",
		buyId: "all-buy"
	},
	{
		id: 2,
		name: "Basil",
		latin: "Ocimum basilicum",
		img: "https://images.unsplash.com/photo-1522259629856-5cd0267d12ac?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=00ba537ab8559b1b08c2f9c3c7703e99&auto=format&fit=crop&w=500&q=60",
		thumb: "../orange/images/thumbnails/basil-thumb-unsplash.jpg",
		color: "chocolate",
		pSource: " herb annuals - India",
		pColor: "Color: verdant green shades",
		pFlavor: "Flavor: sweet, zesty, mildly bitter",
		pUses: "Uses: soups, salads, sauces",
		weight: 2,	//2 oz default size
		cost: "$8.99",
		imgId: "bas-img",
		subId: "bas-sub",
		addId: "bas-add",
		amtId: "bas-amt",
		savId: "bas-sav",
		buyId: "bas-buy"
	},
	{
		id: 3,
		name: "Cardamom",
		latin: "Elettaria cardamomum",
		// img: "https://cdn.pixabay.com/photo/2017/04/20/01/24/cardamom-2244253_960_720.jpg",
		img: "../orange/images/cardamom-sm-Ludmila_ph-pixabay.jpg",
		thumb: "../orange/images/thumbnails/cardamom-thumb-pixabay.jpg",
		color: "chocolate",
		pSource: " seed pods (masticatory) - India",
		pColor: "Color: brown, light green, white (bleached)",
		pFlavor: "Flavor: mildly sweet, zesty",
		pUses: "Uses: tea, coffee, baking, rubs",
		weight: 2,	//2 oz default size
		cost: "$11.99",
		imgId: "car-img",
		subId: "car-sub",
		addId: "car-add",
		amtId: "car-amt",
		savId: "car-sav",
		buyId: "car-buy"
	},
	{
		id: 4,
		name: "Cilantro",
		latin: "Coriandrum sativum",
		img: "https://images.pexels.com/photos/606540/pexels-photo-606540.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260",
		thumb: "../orange/images/thumbnails/cilantro-thumb-pexels.jpg",
		color: "chocolate",
		pSource: " herb annual leaves - Turkey",
		pColor: "Color: bright green",
		pFlavor: "Flavor: fresh, tangy, tart",
		pUses: "Uses: sauces, salads, stir fries",
		weight: 2,	//2 oz default size
		cost: "$3.99",
		imgId: "cil-img",
		subId: "cil-sub",
		addId: "cil-add",
		amtId: "cil-amt",
		savId: "cil-sav",
		buyId: "cil-buy"
	},
	{
		id: 5,
		name: "Cinnamon",
		latin: "Cinnamomum verum",
		img: "https://images.pexels.com/photos/47046/cinnamon-stick-cinnamon-powder-spice-flavoring-47046.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
		thumb: "../orange/images/thumbnails/cinnamon-thumb-pixabay.jpg",
		color: "chocolate",
		pSource: " tree bark - Indonesia",
		pColor: "Color: beige, sandy brown",
		pFlavor: "Flavor: semi-sweet, pungent woody",
		pUses: "Uses: aromatics, cooking and baking",
		weight: 2,	//2 oz default size
		cost: "$7.99",
		imgId: "cin-img",
		subId: "cin-sub",
		addId: "cin-add",
		amtId: "cin-amt",
		savId: "cin-sav",
		buyId: "cin-buy"
	},
	{
		id: 6,
		name: "Cloves",
		latin: "Syzygium aromaticum",
		// img: "https://cdn.pixabay.com/photo/2015/11/18/17/32/cloves-1049598_960_720.jpg",
		img: "../orange/images/cloves-sm-Ajale-pixabay.jpg",
		thumb: "../orange/images/thumbnails/cloves-thumb-pixabay.jpg",
		color: "chocolate",
		pSource: " flowering buds - Indonesia",
		pColor: "Color: deep reddish brown",
		pFlavor: "Flavor: spicy, sharp, peppery",
		pUses: "Uses: aromatics, cooking and baking",
		weight: 2,	//2 oz default size
		cost: "$6.99",
		imgId: "clo-img",
		subId: "clo-sub",
		addId: "clo-add",
		amtId: "clo-amt",
		savId: "clo-sav",
		buyId: "clo-buy"
	},
	{
		id: 7,
		name: "Coriander",
		latin: "Coriandrum sativum",
		// img: "https://cdn.pixabay.com/photo/2013/07/25/12/03/coriander-166989_960_720.jpg",
		img: "../orange/images/coriander-sm-PDPics-pixabay.jpg",
		thumb: "../orange/images/thumbnails/coriander-thumb-pixabay.jpg",
		color: "chocolate",
		pSource: " herb annual seeds - India",
		pColor: "Color: beige, sandy-brown",
		pFlavor: "Flavor:  spicy, tangy lemon",
		pUses: "Uses: aromatics, baking, chilis, rubs",
		weight: 2,	//2 oz default size
		cost: "$3.99",
		imgId: "cor-img",
		subId: "cor-sub",
		addId: "cor-add",
		amtId: "cor-amt",
		savId: "cor-sav",
		buyId: "cor-buy"
	},
	{
		id: 8,
		name: "Cumin",
		latin: "Cuminum cyminum",
		img: "https://images.pexels.com/photos/39073/spices-caraway-garden-eat-39073.jpeg?cs=srgb&dl=bowl-bread-caraway-39073.jpg&fm=jpg",
		thumb: "../orange/images/thumbnails/cumin-thumb-pexels.jpg",
		color: "chocolate",
		pSource: " annual flowering plant seeds - India",
		pColor: "Color: tawny, mustard brown",
		pFlavor: "Flavor: pungent, spicy, smoky",
		pUses: "Uses: chilis, sauces, rubs",
		weight: 2,	//2 oz default size
		cost: "$3.99",
		imgId: "cmn-img",
		subId: "cmn-sub",
		addId: "cmn-add",
		amtId: "cmn-amt",
		savId: "cmn-sav",
		buyId: "cmn-buy"
	},
	{
		id: 9,
		name: "Dill",
		latin: "Anethum graveolens",
		// img: "https://cdn.pixabay.com/photo/2011/06/21/14/43/dill-8104_960_720.jpg",
		img: "../orange/images/dill-sm-Hans-pixabay.jpg",
		thumb: "../orange/images/thumbnails/dill-thumb-pixabay.jpg",
		color: "chocolate",
		pSource: " annual flowering herb - Greece",
		pColor: "Color: light olive green",
		pFlavor: "Flavor: tart, tangy, mildly sour",
		pUses: "Uses: pickling, sauces, dips, rubs",
		weight: 2,	//2 oz default size
		cost: "$7.99",
		imgId: "dil-img",
		subId: "dil-sub",
		addId: "dil-add",
		amtId: "dil-amt",
		savId: "dil-sav",
		buyId: "dil-buy"
	},
	{
		id: 10,
		name: "Ginger",
		latin: "Zingiber officinale",
		// img: "https://cdn.pixabay.com/photo/2017/07/20/20/58/ginger-2523758_960_720.jpg",
		img: "../orange/images/ginger-sm-gate74-pixabay.jpg",
		thumb: "../orange/images/thumbnails/ginger-thumb-pixabay.jpg",
		color: "chocolate",
		pSource: " flowering perennial root - Thailand",
		pColor: "Color: tan, light brown, pale yellow",
		pFlavor: "Flavor: subtle hot tones, spicy",
		pUses: "Uses: tea, beer, baking, candy",
		weight: 2,	//2 oz default size
		cost: "$5.59",
		imgId: "gin-img",
		subId: "gin-sub",
		addId: "gin-add",
		amtId: "gin-amt",
		savId: "gin-sav",
		buyId: "gin-buy"
	},
	{
		id: 11,
		name: "Mustard",
		latin: "Sinapis alba",
		// img: "https://cdn.pixabay.com/photo/2013/12/20/14/01/mustard-231302_960_720.jpg",
		img: "../orange/images/mustard-sm-gokalpiscan-pixabay.jpg",
		thumb: "../orange/images/thumbnails/mustard-thumb-pixabay.jpg",
		color: "chocolate",
		pSource: " annual plant seeds - Nepal",
		pColor: "Color: brown, beige, yellow, white",
		pFlavor: "Flavor: spicy, pungent",
		pUses: "Uses: pickling, sauces, rubs",
		weight: 2,	//2 oz default size
		cost: "$3.49",
		imgId: "mus-img",
		subId: "mus-sub",
		addId: "mus-add",
		amtId: "mus-amt",
		savId: "mus-sav",
		buyId: "mus-buy"
	},
	{
		id: 12,
		name: "Nutmeg",
		latin: "Myristica fragrans",
		// img: "https://cdn.pixabay.com/photo/2017/06/21/16/57/nutmeg-2427844_960_720.jpg",
		img: "../orange/images/nutmeg-sm-scym-pixabay.jpg",
		thumb: "../orange/images/thumbnails/nutmeg-thumb-pixabay.jpg",
		color: "chocolate",
		pSource: " fragrant nutmeg tree seed - India",
		pColor: "Color: beige, sandy-brown",
		pFlavor: "Flavor: semi-sweet, pungent, mildly warm",
		pUses: "Uses: aromatics, cooking and baking",
		weight: 2,	//2 oz default size
		cost: "$4.99",
		imgId: "nmg-img",
		subId: "nmg-sub",
		addId: "nmg-add",
		amtId: "nmg-amt",
		savId: "nmg-sav",
		buyId: "nmg-buy"
	},
	{
		id: 13,
		name: "Oregano",
		latin: "Origanum vulgare",
		// img: "https://cdn.pixabay.com/photo/2017/08/20/19/33/oregano-2662890_960_720.jpg",
		img: "../orange/images/oregano-sm-HansLinde-pixabay.jpg",
		thumb: "../orange/images/thumbnails/oregano-thumb-pixabay.jpg",
		color: "chocolate",
		pSource: " perenial flowering plant leaves - New Zealand",
		pColor: "Color: olive or light green",
		pFlavor: "Flavor: tangy, mildly minty",
		pUses: "Uses: aromatics, sauces, rubs",
		weight: 2,	//2 oz default size
		cost: "$7.99",
		imgId: "org-img",
		subId: "org-sub",
		addId: "org-add",
		amtId: "org-amt",
		savId: "org-sav",
		buyId: "org-buy"
	},
	{
		id: 14,
		name: "Paprika",
		latin: "Capsicum annuum",
		// img: "https://cdn.pixabay.com/photo/2018/09/06/23/12/paprika-3659548_960_720.jpg",
		img: "../orange/images/paprika-sm-Couleur-pixabay.jpg",
		thumb: "../orange/images/thumbnails/paprika-thumb-pixabay.jpg",
		color: "chocolate",
		pSource: " dried tomato pepper - Mexico",
		pColor: "Color: ranges from bright to dusky red",
		pFlavor: "Flavor: semi-sweet, mild to moderate heat",
		pUses: "Uses: sauces, dips, garnish",
		weight: 2,	//2 oz default size
		cost: "$4.99",
		imgId: "ppk-img",
		subId: "ppk-sub",
		addId: "ppk-add",
		amtId: "ppk-amt",
		savId: "ppk-sav",
		buyId: "ppk-buy"
	},
	{
		id: 15,
		name: "Parsley",
		latin: "Petroselinum crispum",
		// img: "https://cdn.pixabay.com/photo/2014/02/07/15/32/parsley-261039_960_720.jpg",
		img: "../orange/images/parsley-sm-AllNikAr-pixabay.jpg",
		thumb: "../orange/images/thumbnails/parsley-thumb-pixabay.jpg",
		color: "chocolate",
		pSource: " biennial flowering plant leaflets - Italy",
		pColor: "Color: brilliant bright green",
		pFlavor: "Flavor: fresh, bitter, mildly minty",
		pUses: "Uses: salads, sauces, garnish",
		weight: 2,	//2 oz default size
		cost: "$2.99",
		imgId: "par-img",
		subId: "par-sub",
		addId: "par-add",
		amtId: "par-amt",
		savId: "par-sav",
		buyId: "par-buy"
	},

	{
		id: 16,
		name: "Rosemary",
		latin: "Rosemarinus officinalis",
		// img: "https://cdn.pixabay.com/photo/2015/12/13/00/11/rosemary-1090419_960_720.jpg",
		img: "../orange/images/rosemary-sm-Hans-pixabay.jpg",
		thumb: "../orange/images/thumbnails/rosemary-thumg-pixabay.jpg",
		color: "chocolate",
		pSource: " flowering evergreen needles - Portugal",
		pColor: "Color: olive or pale green",
		pFlavor: "Flavor: piney, minty, bitter",
		pUses: "Uses: aromatics, rubs, dips, sauces",
		weight: 2,	//2 oz default size
		cost: "$4.99",
		imgId: "ros-img",
		subId: "ros-sub",
		addId: "ros-add",
		amtId: "ros-amt",
		savId: "ros-sav",
		buyId: "ros-buy"
	},
	{
		id: 17,
		name: "Saffron",
		latin: "Crocus sativus",
		// img: "https://cdn.pixabay.com/photo/2017/10/09/22/40/saffron-2835249_960_720.jpg",
		img: "../orange/images/saffron-sm-Xtendo-pixabay.jpg",
		thumb: "../orange/images/thumbnails/saffron-thumb-pixabay.jpg",
		color: "chocolate",
		pSource: " flower dried stigma threads - Spain",
		pColor: "Color: orange, yellow, crimson red",
		pFlavor: "Flavor: hay-like, mildly sweet",
		pUses: "Uses: dyes, sauces, rubs",
		weight: 2,	//2 oz default size
		cost: "$16.99",
		imgId: "saf-img",
		subId: "saf-sub",
		addId: "saf-add",
		amtId: "saf-amt",
		savId: "saf-sav",
		buyId: "saf-buy"
	},
	{
		id: 18,
		name: "Sage",
		latin: "Salvia officinalis",
		// img: "https://cdn.pixabay.com/photo/2018/07/06/17/08/sage-3520814_960_720.jpg",
		img: "../orange/images/sage-sm-_Alicja_-pixabay.jpg",
		thumb: "../orange/images/thumbnails/sage-thumb-pixabay.jpg",
		color: "chocolate",
		pSource: " perennial evergreen shrub leaves - Bulgaria",
		pColor: "Color: grayish or pale green",
		pFlavor: "Flavor: musky, savory, sweet",
		pUses: "Uses: soups, sauces, rubs",
		weight: 2,	//2 oz default size
		cost: "$4.99",
		imgId: "sge-img",
		subId: "sge-sub",
		addId: "sge-add",
		amtId: "sge-amt",
		savId: "sge-sav",
		buyId: "sge-buy"
	},
	{
		id: 19,
		name: "Thyme",
		latin: "Thymus vulgaris",
		// img: "https://cdn.pixabay.com/photo/2013/06/01/03/43/thyme-115379_960_720.jpg",
		img: "../orange/images/thyme-sm-Hans-pixabay.jpg",
		thumb: "../orange/images/thumbnails/thyme-thumb-pixabay.jpg",
		color: "chocolate",
		pSource: " sprig stem, leaflet, and flower - California, USA",
		pColor: "Color: olive or dark green",
		pFlavor: "Flavor: savory, minty, mildly bitter",
		pUses: "Uses: soups, sauces, rubs",
		weight: 2,	//2 oz default size
		cost: "$8.99",
		imgId: "thm-img",
		subId: "thm-sub",
		addId: "thm-add",
		amtId: "thm-amt",
		savId: "thm-sav",
		buyId: "thm-buy"
	},
	{
		id: 20,
		name: "Turmeric",
		latin: "Curcuma longa",
		// img: "https://cdn.pixabay.com/photo/2018/01/18/00/07/turmeric-3089308_960_720.jpg",
		img: "../orange/images/turmeric-sm-stevepb-pixabay.jpg",
		thumb: "../orange/images/thumbnails/turmeric-thumb-pixabay.jpg",
		color: "chocolate",
		pSource: " dried flowering plant root - India",
		pColor: "Color: vibrant yellow-orange",
		pFlavor: "Flavor: musky, spicy, mildly warm",
		pUses: "Uses: dyes, curries, rubs",
		weight: 2,	//2 oz default size
		cost: "$3.99",
		imgId: "tur-img",
		subId: "tur-sub",
		addId: "tur-add",
		amtId: "tur-amt",
		savId: "tur-sav",
		buyId: "tur-buy"
	},
	{
		id: 21,
		name: "Vanilla",
		latin: "Vanilla planifolia",
		// img: "https://cdn.pixabay.com/photo/2014/04/18/13/14/creme-brulee-327134_960_720.jpg",
		img: "../orange/images/vanilla-sm-flomo001-pixabay.jpg",
		thumb: "../orange/images/thumbnails/vanilla-thumb-pixabay.jpg",
		color: "chocolate",
		pSource: " flowering orchid seed pods - Mexico",
		pColor: "Color: dark rusty brown",
		pFlavor: "Flavor: semi-sweet, mildly fruity",
		pUses: "Uses: aromatics, cooking and baking",
		weight: 2,	//2 oz default size
		cost: "$12.99",
		imgId: "vla-img",
		subId: "vla-sub",
		addId: "vla-add",
		amtId: "vla-amt",
		savId: "vla-sav",
		buyId: "vla-buy"
	},
];