{
	"spices"
	[
		{
			"id": "1",
			"name": "Allspice",
			"latin": "Pimenta dioica",
			"img": "https://cdn.pixabay.com/photo/2018/04/22/13/40/cooking-3341063_960_720.jpg",
			"color": "chocolate",
			"pSource": "Source: Pimenta dioica tree berries; Mexico",
			"pColor": "Color: brown, burnt sienna",
			"pFlavor": "Flavor: savory, spicy",
			"pUses": "Uses: pickling, marinades, baking",
			"weight": "2",	//2 oz default size
			"cost": "$4.59",
			"imgId": "all-img",
			"subId": "all-sub",
			"addId": "all-add",
			"amtId": "all-amt",
			"savId": "all-sav",
			"buyId": "all-buy"
		}
	]
}

// export const spices = [
// 	{
// 		id: 1,
// 		name: "Allspice",
// 		latin: "Pimenta dioica",
// 		img: "https://cdn.pixabay.com/photo/2018/04/22/13/40/cooking-3341063_960_720.jpg",
// 		color: "chocolate",
// 		pSource: "Source: Pimenta dioica tree berries; Mexico",
// 		pColor: "Color: brown, burnt sienna",
// 		pFlavor: "Flavor: savory, spicy",
// 		pUses: "Uses: pickling, marinades, baking",
// 		weight: 2,	//2 oz default size
// 		cost: "$4.59",
// 		imgId: "all-img",
// 		subId: "all-sub",
// 		addId: "all-add",
// 		amtId: "all-amt",
// 		savId: "all-sav",
// 		buyId: "all-buy"
// 	},
// 	{
// 		id: 2,
// 		name: "Basil",
// 		latin: "Cinnamomum verum",
// 		img: "https://images.pexels.com/photos/47046/cinnamon-stick-cinnamon-powder-spice-flavoring-47046.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
// 		color: "chocolate",
// 		pSource: "Source: Cinnamomum verum trees; Indonesia",
// 		pColor: "Color: beige, sandy-brown",
// 		pFlavor: "Flavor: semi-sweet, pungent woody flavor",
// 		pUses: "Uses: aromatics, cooking and baking",
// 		weight: 2,	//2 oz default size
// 		cost: "$8.99",
// 		imgId: "bas-img",
// 		subId: "bas-sub",
// 		addId: "bas-add",
// 		amtId: "bas-amt",
// 		savId: "bas-sav",
// 		buyId: "bas-buy"
// 	},
// 	{
// 		id: 3,
// 		name: "Cardamom",
// 		latin: "Cinnamomum verum",
// 		img: "https://images.pexels.com/photos/47046/cinnamon-stick-cinnamon-powder-spice-flavoring-47046.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
// 		color: "chocolate",
// 		pSource: "Source: Cinnamomum verum trees in Indonesia",
// 		pColor: "Color: beige, sandy-brown",
// 		pFlavor: "Flavor: semi-sweet, pungent woody flavor",
// 		pUses: "Uses: aromatics, cooking and baking",
// 		weight: 2,	//2 oz default size
// 		cost: "$6.99",
// 		imgId: "car-img",
// 		subId: "car-sub",
// 		addId: "car-add",
// 		amtId: "car-amt",
// 		savId: "car-sav",
// 		buyId: "car-buy"
// 	},
// 	{
// 		id: 4,
// 		name: "Cilantro",
// 		latin: "Cinnamomum verum",
// 		img: "https://images.pexels.com/photos/47046/cinnamon-stick-cinnamon-powder-spice-flavoring-47046.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
// 		color: "chocolate",
// 		pSource: "Source: Cinnamomum verum trees in Indonesia",
// 		pColor: "Color: beige, sandy-brown",
// 		pFlavor: "Flavor: semi-sweet, pungent woody flavor",
// 		pUses: "Uses: aromatics, cooking and baking",
// 		weight: 2,	//2 oz default size
// 		cost: "$2.99",
// 		imgId: "cil-img",
// 		subId: "cil-sub",
// 		addId: "cil-add",
// 		amtId: "cil-amt",
// 		savId: "cil-sav",
// 		buyId: "cil-buy"
// 	},
// 	{
// 		id: 5,
// 		name: "Cinnamon",
// 		latin: "Cinnamomum verum",
// 		img: "https://images.pexels.com/photos/47046/cinnamon-stick-cinnamon-powder-spice-flavoring-47046.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
// 		color: "chocolate",
// 		pSource: "Source: Cinnamomum verum trees in Indonesia",
// 		pColor: "Color: beige, sandy-brown",
// 		pFlavor: "Flavor: semi-sweet, pungent woody flavor",
// 		pUses: "Uses: aromatics, cooking and baking",
// 		weight: 2,	//2 oz default size
// 		cost: "$7.99",
// 		imgId: "cin-img",
// 		subId: "cin-sub",
// 		addId: "cin-add",
// 		amtId: "cin-amt",
// 		savId: "cin-sav",
// 		buyId: "cin-buy"
// 	},
// 	{
// 		id: 6,
// 		name: "Clove",
// 		latin: "Cinnamomum verum",
// 		img: "https://images.pexels.com/photos/47046/cinnamon-stick-cinnamon-powder-spice-flavoring-47046.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
// 		color: "chocolate",
// 		pSource: "Source: Cinnamomum verum trees in Indonesia",
// 		pColor: "Color: beige, sandy-brown",
// 		pFlavor: "Flavor: semi-sweet, pungent woody flavor",
// 		pUses: "Uses: aromatics, cooking and baking",
// 		weight: 2,	//2 oz default size
// 		cost: "$3.99",
// 		imgId: "clo-img",
// 		subId: "clo-sub",
// 		addId: "clo-add",
// 		amtId: "clo-amt",
// 		savId: "clo-sav",
// 		buyId: "clo-buy"
// 	},
// 	{
// 		id: 7,
// 		name: "Coriander",
// 		latin: "Cinnamomum verum",
// 		img: "https://images.pexels.com/photos/47046/cinnamon-stick-cinnamon-powder-spice-flavoring-47046.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
// 		color: "chocolate",
// 		pSource: "Source: Cinnamomum verum trees in Indonesia",
// 		pColor: "Color: beige, sandy-brown",
// 		pFlavor: "Flavor: semi-sweet, pungent woody flavor",
// 		pUses: "Uses: aromatics, cooking and baking",
// 		weight: 2,	//2 oz default size
// 		cost: "$3.99",
// 		imgId: "cor-img",
// 		subId: "cor-sub",
// 		addId: "cor-add",
// 		amtId: "cor-amt",
// 		savId: "cor-sav",
// 		buyId: "cor-buy"
// 	},
// 	{
// 		id: 8,
// 		name: "Cumin",
// 		latin: "Cinnamomum verum",
// 		img: "https://images.pexels.com/photos/47046/cinnamon-stick-cinnamon-powder-spice-flavoring-47046.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
// 		color: "chocolate",
// 		pSource: "Source: Cinnamomum verum trees in Indonesia",
// 		pColor: "Color: beige, sandy-brown",
// 		pFlavor: "Flavor: semi-sweet, pungent woody flavor",
// 		pUses: "Uses: aromatics, cooking and baking",
// 		weight: 2,	//2 oz default size
// 		cost: "$3.99",
// 		imgId: "cmn-img",
// 		subId: "cmn-sub",
// 		addId: "cmn-add",
// 		amtId: "cmn-amt",
// 		savId: "cmn-sav",
// 		buyId: "cmn-buy"
// 	},
// 	{
// 		id: 9,
// 		name: "Dill",
// 		latin: "Cinnamomum verum",
// 		img: "https://images.pexels.com/photos/47046/cinnamon-stick-cinnamon-powder-spice-flavoring-47046.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
// 		color: "chocolate",
// 		pSource: "Source: Cinnamomum verum trees in Indonesia",
// 		pColor: "Color: beige, sandy-brown",
// 		pFlavor: "Flavor: semi-sweet, pungent woody flavor",
// 		pUses: "Uses: aromatics, cooking and baking",
// 		weight: 2,	//2 oz default size
// 		cost: "$7.99",
// 		imgId: "dil-img",
// 		subId: "dil-sub",
// 		addId: "dil-add",
// 		amtId: "dil-amt",
// 		savId: "dil-sav",
// 		buyId: "dil-buy"
// 	},
// 	{
// 		id: 10,
// 		name: "Ginger",
// 		latin: "Cinnamomum verum",
// 		img: "https://images.pexels.com/photos/47046/cinnamon-stick-cinnamon-powder-spice-flavoring-47046.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
// 		color: "chocolate",
// 		pSource: "Source: Cinnamomum verum trees in Indonesia",
// 		pColor: "Color: beige, sandy-brown",
// 		pFlavor: "Flavor: semi-sweet, pungent woody flavor",
// 		pUses: "Uses: aromatics, cooking and baking",
// 		weight: 2,	//2 oz default size
// 		cost: "$5.59",
// 		imgId: "gin-img",
// 		subId: "gin-sub",
// 		addId: "gin-add",
// 		amtId: "gin-amt",
// 		savId: "gin-sav",
// 		buyId: "gin-buy"
// 	},
// 	{
// 		id: 11,
// 		name: "Mustard",
// 		latin: "Cinnamomum verum",
// 		img: "https://images.pexels.com/photos/47046/cinnamon-stick-cinnamon-powder-spice-flavoring-47046.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
// 		color: "chocolate",
// 		pSource: "Source: Cinnamomum verum trees in Indonesia",
// 		pColor: "Color: beige, sandy-brown",
// 		pFlavor: "Flavor: semi-sweet, pungent woody flavor",
// 		pUses: "Uses: aromatics, cooking and baking",
// 		weight: 2,	//2 oz default size
// 		cost: "$3.49",
// 		imgId: "mus-img",
// 		subId: "mus-sub",
// 		addId: "mus-add",
// 		amtId: "mus-amt",
// 		savId: "mus-sav",
// 		buyId: "mus-buy"
// 	},
// 	{
// 		id: 12,
// 		name: "Nutmeg",
// 		latin: "Cinnamomum verum",
// 		img: "https://images.pexels.com/photos/47046/cinnamon-stick-cinnamon-powder-spice-flavoring-47046.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
// 		color: "chocolate",
// 		pSource: "Source: Cinnamomum verum trees in Indonesia",
// 		pColor: "Color: beige, sandy-brown",
// 		pFlavor: "Flavor: semi-sweet, pungent woody flavor",
// 		pUses: "Uses: aromatics, cooking and baking",
// 		weight: 2,	//2 oz default size
// 		cost: "$4.99",
// 		imgId: "nmg-img",
// 		subId: "nmg-sub",
// 		addId: "nmg-add",
// 		amtId: "nmg-amt",
// 		savId: "nmg-sav",
// 		buyId: "nmg-buy"
// 	},
// 	{
// 		id: 13,
// 		name: "Oregano",
// 		latin: "Cinnamomum verum",
// 		img: "https://images.pexels.com/photos/47046/cinnamon-stick-cinnamon-powder-spice-flavoring-47046.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
// 		color: "chocolate",
// 		pSource: "Source: Cinnamomum verum trees in Indonesia",
// 		pColor: "Color: beige, sandy-brown",
// 		pFlavor: "Flavor: semi-sweet, pungent woody flavor",
// 		pUses: "Uses: aromatics, cooking and baking",
// 		weight: 2,	//2 oz default size
// 		cost: "$7.99",
// 		imgId: "org-img",
// 		subId: "org-sub",
// 		addId: "org-add",
// 		amtId: "org-amt",
// 		savId: "org-sav",
// 		buyId: "org-buy"
// 	},
// 	{
// 		id: 14,
// 		name: "Parsley",
// 		latin: "Cinnamomum verum",
// 		img: "https://images.pexels.com/photos/47046/cinnamon-stick-cinnamon-powder-spice-flavoring-47046.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
// 		color: "chocolate",
// 		pSource: "Source: Cinnamomum verum trees in Indonesia",
// 		pColor: "Color: beige, sandy-brown",
// 		pFlavor: "Flavor: semi-sweet, pungent woody flavor",
// 		pUses: "Uses: aromatics, cooking and baking",
// 		weight: 2,	//2 oz default size
// 		cost: "$2.99",
// 		imgId: "par-img",
// 		subId: "par-sub",
// 		addId: "par-add",
// 		amtId: "par-amt",
// 		savId: "par-sav",
// 		buyId: "par-buy"
// 	},
// 	{
// 		id: 15,
// 		name: "Paprika",
// 		latin: "Cinnamomum verum",
// 		img: "https://images.pexels.com/photos/47046/cinnamon-stick-cinnamon-powder-spice-flavoring-47046.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
// 		color: "chocolate",
// 		pSource: "Source: Cinnamomum verum trees in Indonesia",
// 		pColor: "Color: beige, sandy-brown",
// 		pFlavor: "Flavor: semi-sweet, pungent woody flavor",
// 		pUses: "Uses: aromatics, cooking and baking",
// 		weight: 2,	//2 oz default size
// 		cost: "$4.99",
// 		imgId: "pka-img",
// 		subId: "pka-sub",
// 		addId: "pka-add",
// 		amtId: "pka-amt",
// 		savId: "pka-sav",
// 		buyId: "pka-buy"
// 	},
// 	{
// 		id: 16,
// 		name: "Rosemary",
// 		latin: "Cinnamomum verum",
// 		img: "https://images.pexels.com/photos/47046/cinnamon-stick-cinnamon-powder-spice-flavoring-47046.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
// 		color: "chocolate",
// 		pSource: "Source: Cinnamomum verum trees in Indonesia",
// 		pColor: "Color: beige, sandy-brown",
// 		pFlavor: "Flavor: semi-sweet, pungent woody flavor",
// 		pUses: "Uses: aromatics, cooking and baking",
// 		weight: 2,	//2 oz default size
// 		cost: "$4.99",
// 		imgId: "ros-img",
// 		subId: "ros-sub",
// 		addId: "ros-add",
// 		amtId: "ros-amt",
// 		savId: "ros-sav",
// 		buyId: "ros-buy"
// 	},
// 	{
// 		id: 17,
// 		name: "Saffron",
// 		latin: "Cinnamomum verum",
// 		img: "https://images.pexels.com/photos/47046/cinnamon-stick-cinnamon-powder-spice-flavoring-47046.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
// 		color: "chocolate",
// 		pSource: "Source: Cinnamomum verum trees in Indonesia",
// 		pColor: "Color: beige, sandy-brown",
// 		pFlavor: "Flavor: semi-sweet, pungent woody flavor",
// 		pUses: "Uses: aromatics, cooking and baking",
// 		weight: 2,	//2 oz default size
// 		cost: "$16.99",
// 		imgId: "saf-img",
// 		subId: "saf-sub",
// 		addId: "saf-add",
// 		amtId: "saf-amt",
// 		savId: "saf-sav",
// 		buyId: "saf-buy"
// 	},
// 	{
// 		id: 18,
// 		name: "Sage",
// 		latin: "Cinnamomum verum",
// 		img: "https://images.pexels.com/photos/47046/cinnamon-stick-cinnamon-powder-spice-flavoring-47046.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
// 		color: "chocolate",
// 		pSource: "Source: Cinnamomum verum trees in Indonesia",
// 		pColor: "Color: beige, sandy-brown",
// 		pFlavor: "Flavor: semi-sweet, pungent woody flavor",
// 		pUses: "Uses: aromatics, cooking and baking",
// 		weight: 2,	//2 oz default size
// 		cost: "$4.99",
// 		imgId: "sge-img",
// 		subId: "sge-sub",
// 		addId: "sge-add",
// 		amtId: "sge-amt",
// 		savId: "sge-sav",
// 		buyId: "sge-buy"
// 	},
// 	{
// 		id: 19,
// 		name: "Thyme",
// 		latin: "Cinnamomum verum",
// 		img: "https://images.pexels.com/photos/47046/cinnamon-stick-cinnamon-powder-spice-flavoring-47046.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
// 		color: "chocolate",
// 		pSource: "Source: Cinnamomum verum trees in Indonesia",
// 		pColor: "Color: beige, sandy-brown",
// 		pFlavor: "Flavor: semi-sweet, pungent woody flavor",
// 		pUses: "Uses: aromatics, cooking and baking",
// 		weight: 2,	//2 oz default size
// 		cost: "$8.99",
// 		imgId: "thm-img",
// 		subId: "thm-sub",
// 		addId: "thm-add",
// 		amtId: "thm-amt",
// 		savId: "thm-sav",
// 		buyId: "thm-buy"
// 	},
// 	{
// 		id: 20,
// 		name: "Turmeric",
// 		latin: "Cinnamomum verum",
// 		img: "https://images.pexels.com/photos/47046/cinnamon-stick-cinnamon-powder-spice-flavoring-47046.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
// 		color: "chocolate",
// 		pSource: "Source: Cinnamomum verum trees in Indonesia",
// 		pColor: "Color: beige, sandy-brown",
// 		pFlavor: "Flavor: semi-sweet, pungent woody flavor",
// 		pUses: "Uses: aromatics, cooking and baking",
// 		weight: 2,	//2 oz default size
// 		cost: "$3.99",
// 		imgId: "tur-img",
// 		subId: "tur-sub",
// 		addId: "tur-add",
// 		amtId: "tur-amt",
// 		savId: "tur-sav",
// 		buyId: "tur-buy"
// 	},
// ];